version: "3.9"
services:
  nginx-service:
    image: nginx:1.25.4-alpine@sha256:31bad00311cb5eeb8a6648beadcf67277a175da89989f14727420a80e2e76742
    restart: always
    ports:
      # - 80:80
      - 443:443
      - 3001:3001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/nginx/server.crt
      - ./server.key:/etc/nginx/server.key
      - ./innerLayer.crt:/etc/nginx/innerLayer.crt
    logging:
      driver: none
  outer-layer-service:
    build: ..
    restart: always
    command: outer-layer
    environment:
      - SG_TARGETS=/mnt/targets.yaml
      - SG_INNER_LAYER_CERTIFICATE=/mnt/innerLayer.crt
      - SG_REMOVE_CSPS=true
      - SG_ADMIN_PASSWORD=admin
    ports:
      - 80:3000
    volumes:
      - ./targets.yaml:/mnt/targets.yaml
      - ./innerLayer.crt:/mnt/innerLayer.crt
  inner-layer-service:
    build: ..
    restart: always
    command: inner-layer
    environment:
      - SG_OUTER_LAYER=${SG_OUTER_LAYER:-https://nginx-service:3001}
      - SG_INNER_LAYER_PRIVATE_KEY=/mnt/innerLayer.key
      - SG_OUTER_LAYER_CA=/mnt/server.crt
      - SG_INNER_LAYER_CERTIFICATE=/mnt/innerLayer.crt
    volumes:
      - ./server.crt:/mnt/server.crt
      - ./innerLayer.crt:/mnt/innerLayer.crt
      - ./innerLayer.key:/mnt/innerLayer.key
  example-server-service:
    image: markushinz/example-server:v2.2.88@sha256:e15ebbca5671594bc84aecab7445d3807b6f479a603be8a399a547f778fbced0
    restart: always
