version: "3.9"
services:
  nginx-service:
    image: nginx:1.25.3-alpine@sha256:3923f8de8d2214b9490e68fd6ae63ea604deddd166df2755b788bef04848b9bc
    restart: always
    ports:
      # - 80:80
      - 443:443
      - 3001:3001
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/nginx/server.crt
      - ./server.key:/etc/nginx/server.key
      - ./innerLayer.crt:/etc/nginx/innerLayer.crt
    logging:
      driver: none
  outer-layer-service:
    build: ..
    restart: always
    command: outer-layer
    environment:
      - SG_TARGETS=/mnt/targets.yaml
      - SG_INNER_LAYER_CERTIFICATE=/mnt/innerLayer.crt
      - SG_REMOVE_CSPS=true
      - SG_ADMIN_PASSWORD=admin
    ports:
      - 80:3000
    volumes:
      - ./targets.yaml:/mnt/targets.yaml
      - ./innerLayer.crt:/mnt/innerLayer.crt
  inner-layer-service:
    build: ..
    restart: always
    command: inner-layer
    environment:
      - SG_OUTER_LAYER=${SG_OUTER_LAYER:-https://nginx-service:3001}
      - SG_INNER_LAYER_PRIVATE_KEY=/mnt/innerLayer.key
      - SG_OUTER_LAYER_CA=/mnt/server.crt
      - SG_INNER_LAYER_CERTIFICATE=/mnt/innerLayer.crt
    volumes:
      - ./server.crt:/mnt/server.crt
      - ./innerLayer.crt:/mnt/innerLayer.crt
      - ./innerLayer.key:/mnt/innerLayer.key
  example-server-service:
    image: markushinz/example-server:v2.2.68@sha256:da90908515169e05aba3f5cc0e55ae0899a24ea12d06124c0ee2d26f1878c5a3
    restart: always
