version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - markushinz
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    assignees:
      - markushinz
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - markushinz
