version: "3.7"
services:
  nginx-service:
    image: nginx
    restart: always
    ports:
      # - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/server.crt:/etc/nginx/server.crt
      - ./config/server.key:/etc/nginx/server.key
    logging:
      driver: none
  outer-layer-service:
    build: ./outer-layer
    image: markushinz/socket-gateway-outer-layer:2.1.0
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - SG_TARGETS_FILE=/mnt/targets.yaml
      - SG_INNER_LAYER_PUBLIC_KEY_FILE=/mnt/innerLayer.crt
    ports:
      - 80:80
    volumes:
      - ./config/targets.yaml:/mnt/targets.yaml
      - ./config/innerLayer.crt:/mnt/innerLayer.crt
  inner-layer-service:
    build: ./inner-layer
    image: markushinz/socket-gateway-inner-layer:2.1.0
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NODE_EXTRA_CA_CERTS=/mnt/server.crt
      - SG_OUTER_LAYER=${SG_OUTER_LAYER:-https://nginx-service:3000}
      - SG_INNER_LAYER_PRIVATE_KEY_FILE=/mnt/innerLayer.key
    volumes:
      - ./config/server.crt:/mnt/server.crt
      - ./config/innerLayer.key:/mnt/innerLayer.key
  example-server-service:
    build: ./config/example-server
    restart: always
