targets:
  "localhost":
    hostname: "jsonplaceholder.typicode.com"
  "example.gateway.localhost":
    protocol: "http"
    hostname: "example-server-service"
    port: 3000
  "json.gateway.localhost":
    hostname: "jsonplaceholder.typicode.com"
    policy:
      "/todos/1":
        - "GET"
