version: '3'
services:
  socket-gateway-outer-layer:
    build: https://github.com/markushinz/socket-gateway.git#:outer-layer
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 443:3000
      - 3001:3001
    volumes:
      - ./volume:/usr/src/socket-gateway/outer-layer/config