apiVersion: v1
kind: Service
metadata:
  name: outer-layer-service
spec:
  selector:
    app: outer-layer
  ports:
    - protocol: TCP
      port: 80
      name: app
    - protocol: TCP
      port: 3000
      name: socket
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 3000
