name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: docker/build-push-action@v2
      - name: Compute version
        if: ${{ github.event == 'push' && github.ref == 'refs/heads/master' }}
        run: echo "VERSION=v$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        if: ${{ github.event == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        if: ${{ github.event == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            markushinz/socket-gateway:latest
            markushinz/socket-gateway:${{ env.VERSION }}
      - name: Tag
        if: ${{ github.event == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GIT_COMMITTER_NAME: Markus Hinz
          GIT_COMMITTER_EMAIL: info@markushinz.de
        run: |
          git tag "$VERSION" -m "$VERSION"
          git push origin "$VERSION"
