name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute tag
        run: echo "TAG=v$(./scripts/version.sh)" >> $GITHUB_ENV
      - name: Print tag
        run: echo $TAG
      # - name: Build
      #   uses: docker/build-push-action@v2
