name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker - Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker - Build
        uses: docker/build-push-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=registry,ref=markushinz/socket-gateway:latest
          cache-to: type=inline
      - name: Compute version
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: echo "VERSION=v$(./version.sh)" >> $GITHUB_ENV
      - name: Docker - Login
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker - Push
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            markushinz/socket-gateway:latest
            markushinz/socket-gateway:${{ env.VERSION }}
      - name: Tag
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GIT_COMMITTER_NAME: Markus Hinz
          GIT_COMMITTER_EMAIL: info@markushinz.de
        run: |
          git tag "$VERSION" -m "$VERSION"
          git push origin "$VERSION"
