name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Compute version
        run: echo "VERSION=v$(./scripts/version.sh)" >> $GITHUB_ENV
      # - name: Build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     tags: |
      #       markushinz/socket-gateway:latest
      #       markushinz/socket-gateway:${{ env.VERSION }}
      - name: Tag
        env:
          GIT_COMMITTER_NAME: Markus Hinz
          GIT_COMMITTER_EMAIL: info@markushinz.de
        run: |
          git config --global user.email "you@example.com"
          git tag "$VERSION" -m "$VERSION"
          git push origin "$VERSION"
