name: CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compute version
        run: echo "::set-env name=VERSION::$(./scripts./version)"
      - name: Print version
        run: echo $VERSION
      - name: Build
        uses: docker/build-push-action@v2
