name: Merge
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 3,4 * * *"
jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          number=$(gh pr list --repo ${{ github.repository }} --limit 1 --author app/renovate --json number --jq '.[0].number')
          [[ -n "${number}" ]] && gh pr merge --repo ${{ github.repository }} --auto --squash "${number}" || exit 0
