name: Pull Request
on:
  pull_request:
jobs:
  pullRequest:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.2.0"
      - name: Version and Pack
        run: |
          export VERSION=$(./version.sh)
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          npm version --git-tag-version=false "$VERSION"
          npm ci
          npm run build
          npm pack
          mv "socket-gateway-${VERSION}.tgz" socket-gateway.tgz
      - name: Docker - Build
        uses: docker/build-push-action@v2
