name: Pull Request
on:
  pull_request:
jobs:
  pullRequest:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker - Build
        uses: docker/build-push-action@v2
